<?php
namespace app\bo\controller;

use app\bo\libs\BoController;
use app\bo\model\Invoice as ModelInvoice;
use app\bo\model\OrderUsed;
use think\Request;


class Invoice extends BoController
{

    public function __construct(Request $request)
    {
        $this->model = new ModelInvoice();
        parent::__construct($request);
    }

    public function all()
    {
        $this->assign("stype", "invoice");
        return parent::all(); // TODO: Change the autogenerated stub
    }

    public function searchInvoice()
    {
        $invoiceModel = new ModelInvoice();
        $invoiceModel->where("i.i_noused", "<>", "0");
        $this->assign("type", "invoice");
        return $this->search($invoiceModel, "common/popused");
    }

    public function searchInvoiceNoList()
    {
        $invoiceModel = new ModelInvoice();
        $this->assign("type", "invoice");
        $this->other = "main-pannel";
        return $this->search($invoiceModel);
    }

    public function doAdd()
    {
        $post = $this->request->post();

        $data['i_no'] = trim($post['no']);
        $data['i_content'] = trim($post['content']);
        $data['i_type'] = $post['type'];
        $data['i_money'] = trim($post['money']);
        $data['i_tax'] = trim($post['tax']);
        $data['i_date'] = trim($post['date']);
        $data['i_coid'] = trim($post['coid']);
        $data['i_coname'] = trim($post['coname']);
        $data['i_subject'] = trim($post['subject']);

        $data['i_mid'] = $this->current->m_id;
        $data['i_mname'] = $this->current->m_name;

        $validate = validate('Invoice');

        if($validate->check($data)){

            $data['i_date'] = strtotime($data['i_date']);
            $data['i_money'] = $data['i_noused'] = floatval($data['i_money']);

            $file = $this->request->file('attachment');
            $info =true;

            if(!empty($file)) {
                $baseFolder = DS.'attachment'.DS.date('Y') ;

                $folder = ROOT_PATH . DS . 'public' . $baseFolder;

                if (!is_dir($folder)) {
                    CustomUtils::mkdir_p($folder);
                }

                if(!$file->checkImg()){
                    $info = false;
                }else {
                    $info = $file->move($folder);
                }
            }

            if($info) {
                if ($info !== true) {
                    $data['i_attachment'] = $baseFolder . DS . $info->getSaveName();
                }
                if ($res = $this->model->save($data)) {
                    $ret = ['flag' => 1, 'msg' => '添加成功'];
                } else {
                    $ret = ['flag' => 0, 'msg' => '发生错误'];
                }
            }else{
                $ret = ['flag'=>0,'msg'=>'附件上传失败'];
            }
        }else{
            $ret = ['flag'=>0,'msg'=>$validate->getError()];
        }

        return $ret;
    }

    public function detail($id)
    {
        $data = $this->model->getDataById($id);
        $modelOrderUsed = new OrderUsed();
        $orders = $modelOrderUsed->getOrderUsedByOtid($id,1);
        $this->assign('data',$data);
        $this->assign('orders',$orders);
        return $this->fetch();
    }

    public function update()
    {
        $post = $this->request->post();

        $id = $post['id'];

        $data['i_no'] = $post['no'];
        $data['i_date'] = strtotime(trim($post['date']));
        $data['i_money'] = floatval(trim($post['money']));
        $data['i_type'] = intval($post['type']);
        $data['i_coname'] = trim($post['coname']);
        $data['i_coid'] = intval($post['coid']);
        $data['i_mname'] = trim($post['mname']);
        $data['i_mid'] = intval($post['mid']);
        $data['i_used'] = floatval($post['used']);
        $data['i_noused'] = floatval($post['noused']);

        if( empty($data['i_used']) && !!$post['oused'] ){
            $used = 0;
            foreach( $post['oused'] as $oused){
                $used += floatval($oused);
            }
            $data['i_used'] = $used;
            $data['i_noused'] = $data['i_money'] - $used;
        }

        $res = $this->model->save($data,['i_id'=>$id]);

        if($res){
            $ret = ['flag'=>1,'msg'=>'更新成功'];
        }else{
            $ret = ['flag'=>0,'msg'=>'更新失败'];
        }

        return $ret;

    }

    public function export()
    {
        return $this->doExport();
    }

}