<?php

namespace app\bo\model;

use app\bo\libs\BoModel;
use think\Exception;

class Project extends BoModel
{
    protected $pk = 'p_id';

    protected $searchable = array(
        "p_no" => array(
            "name" => "项目编号",
            "type" => "text",
            "operators" => array(
                "like" => "包含",
                "=" => "等于",
            ),
        ),
        "p_name" => array(
            "name" => "项目名称",
            "type" => "text",
            "operators" => array(
                "like" => "包含",
                "=" => "等于",
            ),
        ),
    );

    public function getList($search = array(), $limit = 20)
    {
        $member = $this->getCurrent();
        $this->alias('p');
        if (!$member->m_isAdmin) {
            $this->join('__CIRCULATION__ c', "p.p_id = c.ci_otid AND c.ci_type = 'project'");
            $this->where("c.ci_mid", "=", $member->m_id);
        }
        $this->field("p.*");
        foreach ($search as $key => $value) {
            $this->where('p.' . $value['field'], $value['opt'], $value['val']);
        }
        if ($limit==false) {
            $list = $this->select();
        } else {
            $list = $this->paginate($limit);
        }
        return $list;
    }

    /**
     * @param $id
     * @return array
     */
    public function getCodeAndNameById($id)
    {
        $data = $this->getDataById($id);
        return ['code' => $data['p_no'], 'name' => $data['p_name']];
    }

    public function import($dataset)
    {
        foreach ($dataset as $key => $data) {
            if ($data['p_type'] != '项目编号') {
                unset($dataset[$key]);
            } else {
                unset($dataset[$key]['p_type']);
            }
        }
        return parent::import($dataset); // TODO: Change the autogenerated stub
    }

    /**
     * @param $dataset
     * @param bool $forceUpdate
     * @return int|void
     */
    protected function doImport($dataset, $forceUpdate = true)
    {

        if (empty($dataset)) return;

        if ($forceUpdate) {
            $sqlPrev = "INSERT INTO `kj_project` (`p_no`,`p_name`) VALUES ";
            $sqlSuffix = " ON DUPLICATE KEY UPDATE `p_name`=VALUES(`p_name`)";
        } else {
            $sqlPrev = "INSERT IGNORE INTO `kj_project` (`p_no`,`p_name`) VALUES ";
            $sqlSuffix = "";
        }

        $i = 0;
        $values = '';

        $db = $this->getQuery();
        $db->startTrans();
        try {
            foreach ($dataset as $data) {

                if (!empty($values))
                    $values .= ",";

                $values .= "('" . $data['p_no'] . "','" . $data['p_name'] . "')";
                $i++;
                if ($i%1000 == 0) { //1000条数据操作一次
                    $sql = $sqlPrev . $values . $sqlSuffix;
                    $res[] = $db->query($sql);
                    $i = 0;
                    $values = '';
                }

            }

            if (!empty($values)) {
                $sql = $sqlPrev . $values . $sqlSuffix; //var_dump($sql);die;
                $res[] = $db->query($sql);
            }
            $db->commit();
            return $res;

        }catch (\Exception $e){
            $db->rollback();
            $log = 'Exception - '. $e->getMessage();
            CustomUtils::writeImportLog($log,'project');
        }

    }

    public function getProject($no, $name = false)
    {

        if (empty($no)) {
            $project = false;
        } else {
            $project = $this->where('p_no', '=', $no)->find();
            if (empty($project)) {
                $pid = $this->insertGetId(['p_no' => $no, 'p_name' => $name]);
                $project = new static(['p_id' => $pid, 'p_no' => $no, 'p_name' => $name]);
            }
        }

        return $project;

    }

}